# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:17.5.0
    steps:
      - checkout
      - run:
          name: check node version
          command: node --version
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: typescript compilation
          command: yarn compile:tsc
      - run:
          name: Run test
          command: yarn test
