# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:17.5.0
      - image: circleci/mongo:3.6
        environment:
          MONGO_USERNAME: mongouser
          MONGO_PASSWORD: mongopass
    steps:
      - checkout
      - run:
          name: Waiting for Mongo
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - run:
          name: Connecting to mongodb
          command: mongo --eval "printjson(db.apikeys.count());" anonymous-api
      - run:
          name: check node version
          command: node --version
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: typescript compilation
          command: yarn compile:tsc
      - run:
          name: Run test
          command: yarn test
